defaults: &defaults
  docker:
    - image: quay.io/pantheon-public/terminus-plugin-test:1.x
  working_directory: ~/work/wp
  environment:
    TZ: "/usr/share/zoneinfo/America/Los_Angeles"
    TERM: dumb

version: 2
jobs:
    test:
        <<: *defaults
        steps:
            - checkout
            - run:
                name: Set up environment
                command: ./.circleci/set-up-globals.sh
            - run:
                name: Prepare
                command: ./.circleci/prepare.sh
            - run:
                name: Test
                command: ./.circleci/test.sh --strict
            - run:
                name: Cleanup
                command: ./.circleci/cleanup.sh
    automerge:
        <<: *defaults
        steps:
            - checkout
            - run:
                name: Merge the default branch back to the master branch
                command: ./.circleci/automerge.sh

workflows:
  version: 2
  wordpress:
    jobs:
      - test
      - automerge:
          requires:
            - test
          filters:
            branches:
              only:
                - default
